# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#ka:
#  languageCode: ka
#  contentDir: content/ka
#  title: გ. ნადარეიშვილი
#  params:
#    description: 'მკვლევარი მათემატიკოსი და მათემატიკის ექსპერტი'
#  menu:
#    main:
#  - name: მთავარი
#    url: '#about'
#    weight: 10
#  - name: პუბლიკაციები
#    url: '#publications'
#    weight: 20
#  - name: მოხსენებები
#    url: '#talks'
#    weight: 30
#  - name: სწავლება
#    url: '#teaching'
#    weight: 40
#  - name: სემინარები
#    url: '#seminars'
#    weight: 50
#  #- name: Posts
#  #  url: '#posts'
#  #  weight: 60
#  - name: კონტაქტი
#    url: '#contact'
#    weight: 70